# Generated by Django 3.2.3 on 2021-06-11 23:58

from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smiles', models.CharField(max_length=1000, verbose_name='SMILES*')),
                ('expdata', models.TextField(max_length=1000, verbose_name='コード*')),
                ('name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='製品名')),
                ('seller', models.CharField(blank=True, max_length=1000, null=True, verbose_name='卸業者')),
                ('properties', models.TextField(blank=True, max_length=1000, null=True, verbose_name='性状')),
                ('comments', models.TextField(blank=True, max_length=1000, null=True, verbose_name='その他')),
                ('HNMR', models.FileField(blank=True, null=True, upload_to='', verbose_name='1H NMR')),
                ('CNMR', models.FileField(blank=True, null=True, upload_to='', verbose_name='13C NMR')),
                ('IR', models.FileField(blank=True, null=True, upload_to='', verbose_name='IR')),
                ('UV_vis', models.FileField(blank=True, null=True, upload_to='', verbose_name='UV_vis')),
                ('XRD', models.FileField(blank=True, null=True, upload_to='', verbose_name='XRD')),
                ('mol', system.models.MolField(blank=True, db_index=True, null=True)),
                ('mw', models.FloatField(blank=True, db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bottle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_No', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Lot No.')),
                ('ordered', models.BooleanField(default=False, verbose_name='注文済み')),
                ('delivered', models.BooleanField(default=False, verbose_name='納品済み')),
                ('compound', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='system.inventry', verbose_name='comBB')),
            ],
        ),
    ]
